name: Workflow for greeting service

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Clone repository.
        uses: actions/checkout@v3

      - name: Run tests.
        run: ./gradlew clean test

  build:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Clone repository.
        uses: actions/checkout@v3

      - name: Build project.
        run: ./gradlew clean bootJar

      - name: Build a project image and send it to docker storage.
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          echo ${{ env.ACCOUNT_NAME }} 
          docker build -t ${{ env.ACCOUNT_NAME }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }} .
          docker push ${{ env.ACCOUNT_NAME }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Clear docker objects.
        run: |
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker system prune -a -f

      - name: Pull project updated image and create new docker container.
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker pull ${{ env.ACCOUNT_NAME }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}
          docker run -d -p 80:8080 \
           --name ${{ env.CONTAINER_NAME }} \
           ${{ env.ACCOUNT_NAME }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}