name: Workflow for greeting service

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: run tests
        run: ./gradlew test

  print:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: print message
        run: echo 'Finish!'